### ISSUE TITLE
How does Cloudbridge determine an Azure storage account?

### ISSUE THREAD

**Issue by VJalili** [CloudVE/cloudbridge#135]
I use the following script to read an object named `abc` from Azure: 

```python 
    config = {'azure_subscription_id': " ... ",
              'azure_client_id': " ... ",
              'azure_secret': " ... ",
              'azure_tenant': " ... "}
    
    connection = CloudProviderFactory().create_provider(ProviderList.AZURE, config)
    bucket_obj = connection.storage.buckets.get(" ... ")
    key = bucket_obj.objects.get("abc")
```
Running this script, I get the following error: `Azure Error: AuthorizationFailed`.

(I tested my credentials for getting the same object using a custom code (without using cloudbridge), and it works.)

I am guessing that the issue is cause by how _storage account_ is determined in cloudbridge:

https://github.com/CloudVE/cloudbridge/blob/ce6defec3f49c770ee147b427da295a7e65d7b7b/cloudbridge/cloud/providers/azure/provider.py#L47-L51

This will cause cloudbridge to attempt read/write `cloudbridge` storage account: 

```shell
/subscriptions/ ... /resourcegroups/cloudbridge
```
However, I don't have a storage account with `cloudbridge` name; hence, (I think that is why) I get authorization error. 

```shell
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    bucket_obj = connection.storage.buckets.get("my_container")
  File ".../cloudbridge/cloudbridge/cloud/providers/azure/services.py", line 203, in get
    bucket = self.provider.azure_client.get_container(bucket_id)
  File ".../cloudbridge/cloudbridge/cloud/providers/azure/provider.py", line 106, in azure_client
    self._initialize()
  File ".../cloudbridge/cloudbridge/cloud/providers/azure/provider.py", line 120, in _initialize
    resource_group_params)
  File ".../cloudbridge/cloudbridge/cloud/providers/azure/azure_client.py", line 281, in create_resource_group
    create_or_update(name, parameters)
  File ".../Venvs/cloudbridge/lib/python2.7/site-packages/azure/mgmt/resource/resources/v2018_05_01/operations/resource_groups_operations.py", line 151, in create_or_update
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: AuthorizationFailed
```

**Comment by VJalili** [comment]
I fixed the issue, and here is what I did to fix it, and my recommendations:

- [ ] As explained [in the cloudbridge docs](http://cloudbridge.readthedocs.io/en/latest/getting_started.html#create-a-provider), the following keys are the _only required_ configuration arguments to initialize an instance of Azure backend: 
```python
config = {'azure_subscription_id': ' ... ',
          'azure_client_id': ' ... ',
          'azure_secret': ' ... ',
          'azure_tenant': ' ... '}
```
While these information could be sufficient for compute instances, they are inadequate for using Azure BLOB Storage. Hence, the following keys are also _required_ and _should_ be included in the config: 

```python
'azure_storage_account': ' ... ',
'azure_resource_group': ' ... '
``` 

- [ ] When the aforementioned keys are missing from the config, cloudbridge attempts to create a storage account with `storageacccloudbridge` label under `cloudbridge` resource group: 

https://github.com/CloudVE/cloudbridge/blob/ce6defec3f49c770ee147b427da295a7e65d7b7b/cloudbridge/cloud/providers/azure/provider.py#L47-L51

This action requires a **subscription-level Owner role**, which is a very strong requirement because users of an account are not likely to have such high-level privileges to grant service principle used by cloudbridge with an owner role. Regardless, this attempt throws the following error:

```shell
Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Storage/storageAccounts/storageacccloudbridge' under resource group 'cloudbridge' was not found.
```
Therefore, I recommend that cloudbridge does not attempt to create a storage account, if an storage account is not provided or the provided account does not exist; and instead just throw an error and inform the user that the requested account is missing. 

- [ ] [`AzureBucketContainer`](https://github.com/CloudVE/cloudbridge/blob/09e7e2497bbdfe82f3db4047c6768a4ac24a7e54/cloudbridge/cloud/providers/azure/resources.py#L356) does not implement `exists` method as defined in the [`BucketContainer`](https://github.com/CloudVE/cloudbridge/blob/09e7e2497bbdfe82f3db4047c6768a4ac24a7e54/cloudbridge/cloud/interfaces/resources.py#L2403) interface. Without this method, I receive the following error:
```shell
TypeError: Can't instantiate abstract class AzureBucketContainer with abstract methods exists
```
Therefore, IMO, the `exist` method needs to be implemented.

**Comment by afgane** [comment]
Interpreting this, it sounds like `azure_storage_account` and `azure_resource_group` are required if the account does not have the *owner* role. If the account has the given role, CB will create the necessary resources and proceed. So my take on this is that we if the values are not provided, we attempt to create the resources and if that fails, raise an exception saying we were not able to create the required resources, possibly due to lack of permissions, and that the user should supply them. That way, operations will just work if the account has proper permissions or be informational if not. How does that sound?

**Comment by VJalili** [comment]
I think at the moment it works as you said. However, IMHO and based on the _principle of least privilege_, CB should not assume that a user (or a service principal) has such access. Because if credentials are compromised, they provide anyone in possession of credentials, with an unlimited access to the tenant account. Therefore, I think it would be safer if: (a) CB treats `azure_storage_account` and `azure_resource_group` as required arguments, and (b) throws an error if the an account as provided in `azure_storage_account` does not exist.

**Comment by afgane** [comment]
The way I see it is that CB is a library, not an application and it just normalizes the requests vs. imposing usage requirements. If, for example, from CloudLaunch or Galaxy standpoint, we'd like to enable seamless use of Azure without requiring the user to get involved with the internal provider concepts, I feel it should be possible. Also, for power-users that want to create higher-level applications using CB, they may need such capabilities.

**Comment by nuwang** [comment]
It looks to me like a critical issue here is the lack of the exists() method or a corresponding test, which should have caught this issue at the very outset. Nice work tracking that down!

WRT to the storage account, I can see why both sides of the argument are appealing. On the one hand, we use cloudbridge for power-user functions, and in this case, it's a hassle to have to manually create the storage account and learn additional azure concepts, when cloudbridge can handle all that transparently. We are not violating the principle of least privilege here, because at no point are we asking for or recommending the use of higher privileges, only using them if the user happens to already has those privileges, and recommending the correct behaviour in the exception message.

On the other hand, I see an advantage in making the azure_storage_account a mandatory parameter to the provider. This indicates early on that this is in fact, a necessary parameter for dealing with storage, and should be externally created since runtime creation is likely to fail. We could have users who test their apps (unknowingly) on a higher privilege account, only to have it fail when tested on a lower privilege one. 

BTW, has it been completely verified that you need ownership rights to create a storage account? (I ask because Alex isn't running into this?) What about a resource group? because I think that's auto created too. Why is it that storage accounts need Ownership and resource groups don't?

**Comment by VJalili** [comment]
> It looks to me like a critical issue here is the lack of the exists() method or a corresponding test, which should have caught this issue at the very outset. Nice work tracking that down!

I think this was a problem with my branch; updating it I don't see `exists` method in `BucketContainer` interface. (I think you have removed `exists` method whit [this commit](https://github.com/CloudVE/cloudbridge/commit/ffa93759fc22204b12c3791c2c438b8c0ca6433c#diff-94d4aadb8e485e76cac35132939f5383).)

**Comment by afgane** [comment]
I think `get` should be the method used instead now.

**Comment by afgane** [comment]
Partially addressed in https://github.com/CloudVE/cloudbridge/commit/3e9a301d63091b329bd01bc8c36867694a22d19e#diff-072844f302e1dd21f708eeb73d61557fR318.

**Comment by VJalili** [comment]
@afgane that sounds good, thanks! I think that should be enough for now.
