### ISSUE TITLE
Subnet test race condition

### ISSUE THREAD

**Issue by almahmoud** [CloudVE/cloudbridge#154]
When testing subnet creation, given that the CIDR_Block is fixed, there is a conflict if two tests are running at the same time. Mostly seen in Azure tests (probably because they run slower thus increasing the time between creation and deletion)
https://github.com/CloudVE/cloudbridge/blob/master/test/test_network_service.py#L103

**Comment by nuwang** [comment]
Perhaps we can create a new network for this test alone, instead of using the shared subnet?

**Comment by almahmoud** [comment]
That might be a problem with the VPC limit in AWS being 5, and only having 2 consistent slots on the account, so we'd avoid this problem but likely intermittently hit the VPC limit again for which we refactored the tests a few weeks ago. However, we could wrap this specific test in a retry to avoid the conflict in both situations (new network limit or same network subnet conflict), as in both cases the conflicting resources would get deleted when the other test passes

**Comment by nuwang** [comment]
One reason to be wary of the idea of retries is that they could perhaps make genuinely solvable race conditions fly under the radar. As I recall, several were caught and fixed in the last few weeks, and some of those may not have manifested themselves with a retry? I can't recall whether that's actually the case though, do you remember?

**Comment by nuwang** [comment]
@almahmoud Is this fixed now?

**Comment by almahmoud** [comment]
We are now creating a network again, it is fixed unless we hit VPC limits on AWS again
