### ISSUE TITLE
GCE Description Decision

### ISSUE THREAD

**Issue by almahmoud** [CloudVE/cloudbridge#176]
For GCE, we are using the built-in (unchangeable) description at create-time and a label with key 'description' within the setter for some resources (e.g.: snapshot).
We should likely decide whether we want to use the built-in description and remove the setter, or only use a changeable label for descriptions.

**Comment by afgane** [comment]
All the other providers use a tag (AWS & Azure) or a changeable property (OpenStack) so as things stand, we should probably go the route of using a changeable label on GCE as well.

**Comment by nuwang** [comment]
It doesn't look like we have too much of a choice, but the performance implications are worrying - we are already storing a fair amount of data in project metadata. Since project metadata is written as a [whole](https://cloud.google.com/compute/docs/reference/rest/v1/projects/setCommonInstanceMetadata), and doesn't appear to be updated in parts can't be updated in parts, the more data we store, the slower updates will get. The potential for fingerprint conflicts also get higher.

For infrequently created/updated objects, this may not be much of an issue. The problem will become more severe for objects that may be frequently created and destroyed - like volumes - especially at scale.

**Comment by almahmoud** [comment]
I changed it for Volumes and Snapshots in https://github.com/CloudVE/cloudbridge/commit/424216747b0370b94031621c842e7b480e5a46d6, and added the description at create-time as to mitigate the problem Nuwan mentioned. The performance impact is thus only for changing descriptions, but that shouldn't be a very repeated operation at scale.
GCEVMFirewallRules have a changeable description, so for the firewall description we are using those. I also added setters for all Firewall descriptions as they were missing on some providers in: https://github.com/CloudVE/cloudbridge/commit/2c2bdbdaf4a6b22508ec16930483de6455d5d572.
Closing this issue, re-open if anything else needs to be done here.
