### ISSUE TITLE
Starting and stopping of AWS instance

### ISSUE THREAD

**Issue by neelesh-a** [CloudVE/cloudbridge#244]
I am very new to this library. Just downloaded the same today and started experimenting.

I could not find a way to "Start" and "Stop" an AWS Instance. Please let me know if I am missing something, is there any way to do so. This seem to be basic operation which should have been available.

**Comment by nuwang** [comment]
@neelesh-a Yes, you're right. It looks like they never got added because we haven't needed to use them so far, but we'd welcome a PR. It's a matter of adding the two methods to the interface here: https://github.com/CloudVE/cloudbridge/blob/307c34c4c4c3be7ddf04edce461c5dbaafe57201/cloudbridge/interfaces/resources.py#L566
And then implementing it for each cloud.

**Comment by abhi005** [comment]
@nuwang Hey, I would like to work on this issue. And since this is one of the mandatory requirements for my course work, will make sure that it gets completed.

**Comment by abhi005** [comment]
hey @nuwang can you please update on this

**Comment by nuwang** [comment]
@abhi005 Sorry I missed your original message. We'd be happy to accept a PR on this. Let us know if you need any help.

**Comment by nuwang** [comment]
Fixed in: https://github.com/CloudVE/cloudbridge/pull/271
