### ISSUE TITLE
Way to get all gateways and floating IPs?

### ISSUE THREAD

**Issue by selshowk** [CloudVE/cloudbridge#254]
Thanks for this very nice library!  I've been experimenting with some code in the getting started guide and it mostly works very well but I am hitting one difficulty: I'm having trouble consistently cleaning up resources I've created.

Most resources can be listed or queried with "find" but the exception for this seems to be gateways and floating ips.  From the API I see that its possible to get those if they are attached to a network object (via network.gateways.list() and then gateway.floating_ips.find()) but if a gateway is not attached to a network then I have found no way to acess it via the API.  Is this correct?

Using the AWS provider I have been able to create a network, subnet, gateway, ip, fw and instance and then delete them.  But sometimes the gateway fails to delete for some reason but the network (and other resources) do get deleted.  At this point the only way for me to delete the gateway is manually via the AWS console: I don't see any way to access it via the api.  

This is a problem because AWS imposes stringent limits on gateways and floating IPs so if I don't clean up resources I quickly get in a situation where I have to manually clean up. Do you know any way around this?

**Comment by nuwang** [comment]
@selshowk Do you have a minimal snippet by chance where you can reproduce this issue? I think that would be helpful to identify what's blocking the gateway from being deleted.

Ideally, we'd fix this at a cloudbridge level so that the gateway gets deleted consistently. Sometimes, it may be a matter of waiting for the resources to be deleted. We also have a cleanup_helper that's often useful for things like this: https://github.com/CloudVE/cloudbridge/blob/d6708dd420c834bef1b998b6defe823b434f0a11/tests/test_block_store_service.py#L80

If you want to directly delete the gateway, you can access botodirectly through `provider.ec2_conn` (https://github.com/CloudVE/cloudbridge/blob/0d1a7aa98273b424b7b02675b90b18b418e7853f/cloudbridge/providers/aws/provider.py#L77) but the obvious downside is that it won't be cloud independent anymore.

hth!

**Comment by selshowk** [comment]
Thanks for the fast response!

I've more or less copied the [getting_started page](http://cloudbridge.cloudve.org/en/latest/getting_started.html) into a `create_vm` function (which creates a network, gateway, fw, vm, public IP, etc) and then when its done I try to delete the resources using this function (also adapted from that link but expanded a bit):
```
def delete_full(base_name=BASE_NAME):
    # delete floating IPs
    for net in provider.networking.networks.find(label=f'{base_name}-network'):
        print(net)
        for gateway in net.gateways.list():
            print(gateway)
            # we have to be careful to only delete IPs that are associated with
            # our VMs
            for inst in provider.compute.instances.find(label=f'{base_name}-instance'):
                for ip in inst.public_ips:
                    for fip in  gateway.floating_ips.find(public_ip=ip):
                        inst.remove_floating_ip(fip)
                        fip.delete()
                        print(fip)
            #for fip in gateway.floating_ips.list():
                #fip.delete()
    for inst in provider.compute.instances.find(label=f'{base_name}-instance'):
        inst.delete()
        inst.wait_for([InstanceState.DELETED, InstanceState.UNKNOWN],
               terminal_states=[InstanceState.ERROR])  # Blocking call
    # delete filrewalls
    for fw in provider.security.vm_firewalls.find(label=f'{base_name}-firewall'):
        fw.delete()
    # detatch subnets and gateways and delete routers
    for router in provider.networking.routers.find(label=f'{base_name}-router'):
        for subnet in router.subnets:
            for gateway in subnet.network.gateways.list():
                router.detach_gateway(gateway)
                gateway.delete()
            router.detach_subnet(subnet)
            subnet.delete()
        router.delete()
    # delete subnet, gateways then network
    for net in provider.networking.networks.find(label=f'{base_name}-network'):
        # it seems we can sometimes fail to delete the router above so we do
        # it again here
        for router in provider.networking.routers.list():
            if router.network_id == net.id:
                router.delete()
        for subnet in net.subnets.list():
            subnet.delete()
        for gateway in net.gateways.list():
            gateway.delete()
        net.delete()
    # delete any key pairs
    for kp in provider.security.key_pairs.find(name=f'{base_name}-keypair'):
        kp.delete()
```
Running the above function after creating resources as described in the getting started link gives following exception:
```
ClientError: An error occurred (Gateway.NotAttached) when calling the DetachInternetGateway operation: resource igw-XXXXX is not attached to network vpc-XXXX
```
This error happens when I'm trying to detach the gateway above.  I suspect I can change the logic to avoid this error but the bigger issue remains: after this code is run the gateway is not longer attached to any network I have access to.  

If I retrieve the network and check I get:
```
In [10]: net.gateways.list()
Out[10]: []
```
But if I check the aws console the gateway **does exist** and is detached.  

If I run my `delete_full()` function a second time (which should be possible as its written to work in any state) I get the following exception:
```
ClientError: An error occurred (DependencyViolation) when calling the DeleteRouteTable operation: The routeTable 'rtb-0595ce9c6003f5a35' has dependencies and cannot be deleted.
```
Not sure if this is related to the above or a different issue.

My goal here is to be able to **robustly** delete any resource associated with the VM I create even in the situation when the creation code has only partially run (e.g. an exception at some point in the code) or if e.g. it gets run more than once (which generate multiple copies of resources with the same label).  Because i want to use this in an automated way, its important that things don't stick around.  My delete_all() function would be able to robustly delete all resources but it can get into a state where it can't access a gateway anymore (and I'm not even sure there's any way to access that gateway via cloudbridge since its not attached to any network).

One caveat is that I'm noticing my VM-launch code is generating two networks (rather than one) so that might be partially related to the issue above but it doesn't change the fact that its possible to create a set of resources that cannot be cleaned up via the API.

**Comment by nuwang** [comment]
@selshowk I think you can increase the reliability of your deletes by changing the pattern of how you perform the delete. The tutorial example is not very descriptive on this point, but a common pattern we use is this: https://github.com/CloudVE/cloudbridge/blob/0d1a7aa98273b424b7b02675b90b18b418e7853f/tests/test_network_service.py#L208

All the cleanup_helper does is to make sure that even if an exception occurs, the delete operations will continue. So for example, you ran into the issue: `ClientError: An error occurred (Gateway.NotAttached) when calling the DetachInternetGateway operation: resource igw-XXXXX is not attached to network vpc-XXXX`, which means that the subsequent delete operation on the gateway probably never ran, which is what may have left the orphaned gateway behind.

So I'd rewrite the delete function to be something along the lines of:
```
def delete_full(base_name=BASE_NAME):
    # delete floating IPs
    for net in provider.networking.networks.find(label=f'{base_name}-network'):
        print(net)
        for gateway in net.gateways.list():
            print(gateway)
            # we have to be careful to only delete IPs that are associated with
            # our VMs
            for inst in provider.compute.instances.find(label=f'{base_name}-instance'):
                for ip in inst.public_ips:
                    for fip in  gateway.floating_ips.find(public_ip=ip):
                        with cb_helpers.cleanup_action(lambda: fip.delete()):
                            inst.remove_floating_ip(fip)
                        print(fip)
    for inst in provider.compute.instances.find(label=f'{base_name}-instance'):
        with cb_helpers.cleanup_action(lambda: inst.delete()):
                inst.wait_for([InstanceState.DELETED, InstanceState.UNKNOWN],
                    terminal_states=[InstanceState.ERROR])  # Blocking call
....
```

It's important to nest and order the cleanup_actions so that all resources are deleted in the correct order, but that's generally up the way you create resources in your particular use case.

hth!

**Comment by selshowk** [comment]
Thanks for all your help @nuwang.  I will use the cleanup_action to improve my deletion code (and can also write the function more defensively) but I am just worried that its possible to lose access to the gateway in general.  I guess the solution is for me to implement gateway listing code for each provider.  Alternatively I might try to use public-ips for each instance (as in the issue #255 ) which would bypass the need for creating gateways.

**Comment by nuwang** [comment]
@selshowk I understand what you mean. The reason for the current design is that Gateways do not exist in the same form across all clouds. For example, on OpenStack, it's just a network with external connectivity. So allowing gateways to be listed for delete won't work the same way across clouds. Therefore, from a cloud portability perspective, the only way out we've found is to delete in the correct order (or to write cloud specific code). Our test code is a pretty good point of reference, because we create and delete networks, gateways etc. and it's been pretty ok with no left-over gateways. Would be great to hear how it goes for you:
yhttps://github.com/CloudVE/cloudbridge/blob/0d1a7aa98273b424b7b02675b90b18b418e7853f/tests/test_network_service.py#L217

**Comment by nuwang** [comment]
@selshowk Have updated the docs with a better example of this: https://github.com/CloudVE/cloudbridge/pull/260
