### ISSUE TITLE
Install documentation is not clear enough regarding which module is needed for which provider

### ISSUE THREAD

**Issue by Jegeva** [CloudVE/cloudbridge#309]
The documentation makes it not clear enough what python modules are required to use what cloup provider.
After installation i was a little be dumbfounded to see that only the AWS exemple was working 
(because i had boto3 installed on my machine) but not the others.

I have to dig into the initialization to understand that i was missing modules that were not taken care of by pip.

**Comment by nuwang** [comment]
@Jegeva Thanks for reporting this. This was a recent change and looks like some documentation was overlooked. Fixed in linked issue. Use `pip install cloudbridge[full]`.

 You can also install specific providers as detailed here: http://cloudbridge.cloudve.org/en/latest/topics/install.html#single-provider-installation
