### ISSUE TITLE
Azure - ability to use multiple resource groups

### ISSUE THREAD

**Issue by patchkez** [CloudVE/cloudbridge#320]
We have sub-teams locked to their own resource groups. Then we have dedicated resource group which has virtual network assigned, which can be used by these sub-teams. Cloudbridge support only one resource group which is used for all operations. 

Would it be possible to add option e.g. to specify other resource group used e.g. for picking network resources?

**Comment by patchkez** [comment]
Can someone please have a look on this issue? I can provide more info if it is not clear from the  issue description.

**Comment by almahmoud** [comment]
Hey @patchkez , thank you for the suggestion. I think adding the feature is doable, but I cannot guarantee that anyone has time/bandwidth to implement it in the near future. If you start the implementation, I would be willing to review the PR. Otherwise, it might take a bit, but we'll hopefully get time to address it eventually

**Comment by nuwang** [comment]
Another option here is to instantiate a new provider instance for the new resource group. Would that approach not work as a workaround?

**Comment by patchkez** [comment]
@almahmoud could you please review PR #321 which should fix this issue?
