### ISSUE TITLE
Zone parameter in subnet.create()

### ISSUE THREAD

**Issue by nuwang** [CloudVE/cloudbridge#63]
Do we need the zone parameter anymore? It would seem like we should either make it mandatory or remove it altogether?

**Comment by afgane** [comment]
Amazon's subnets are zone-specific. So if a user requests placement for a launched instance, we need to be able to specify the zone where to create the subnet. An alternative is to create the subnet in every zone in the region but then the `create` method would return multiple subnets for AWS, which makes no sense. On the other hand, OpenStack ignores subnet zone altogether. 

So it's easy to require it and simply ignore it for OS. If required, it may make the CloudLaunch a bit more complicated because it will be required to supply the subnet while ensuring it matches optionally selected placement.

**Comment by nuwang** [comment]
conclusion: make zone mandatory for subnet.create()

**Comment by Dyex719** [comment]
All the instances of subnet.create() [https://github.com/gvlproject/cloudbridge/search?l=Python&q=subnets.create&type=&utf8=%E2%9C%93] are included in the function create_subnet() [https://github.com/gvlproject/cloudbridge/blob/0fb03d21102466250be5a1d8056dd05091f690e5/cloudbridge/cloud/base/resources.py/#L940] which takes a 'zone=None' parameter. 
Should changing this to 'zone=zone' be enough?

**Comment by Dyex719** [comment]
I'm not sure whether I should add a  zone parameter to https://github.com/gvlproject/cloudbridge/blob/18305a38da71185041f4785ada12cb6498cde586/test/test_network_service.py#L78

**Comment by nuwang** [comment]
@Dyex719 Yes, that sounds like a good plan. Starting with changing the test to include the zone parameter would probably be best.
```
 return self.provider.networking.subnets.create( 
     network=net, cidr_block="10.0.0.1/24", name=name,
     zone=helpers.get_provider_test_data(self.provider, 'placement')
```

**Comment by Dyex719** [comment]
Please refer to https://github.com/gvlproject/cloudbridge/pull/101.
Also should what I mentioned in above be done? That is, adding a zone parameter to https://github.com/gvlproject/cloudbridge/pull/101 to make it mandatory.

**Comment by afgane** [comment]
Thanks for taking this on. Modifying the test is only a part of this though. It's also necessary to modify the interface for the`SubnetService` `create` method (https://github.com/gvlproject/cloudbridge/blob/master/cloudbridge/cloud/interfaces/services.py#L743) by removing the default `None` argument to the `zone` parameter. After that, the same should be done for each of the provider implementations. Finally, an update to the docs in the interface file to just remove the word _optional_ for the `zone` parameter.

**Comment by afgane** [comment]
Also, see the Travis tests output - there's a flake8 error: https://travis-ci.org/gvlproject/cloudbridge/jobs/293663371#L584

**Comment by afgane** [comment]
Done in #101.
